# Generated by Django 5.0 on 2023-12-23 17:55

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat('first_name', models.Value(' '), 'last_name'), output_field=models.CharField(max_length=511)),
        ),
    ]
